/** tw test -- run project tests (tests/*.test.ts) via bun:test. */

import { join } from "node:path";
import { createRequire as _cr } from "node:module";
const _require: NodeRequire = _cr(import.meta.url);
import { existsSync, readdirSync, statSync } from "node:fs";

function collectTests(dir: string, out: string[]): void {
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) collectTests(full, out);
    else if (/\.test\.(ts|tsx|js)$/.test(entry)) out.push(full);
  }
}

/**
 * Published installs do not have the monorepo's `@tw/*` workspace packages,
 * but scaffolded tests import `@tw/server/tw/testing`. Create a tiny shim in
 * the app's node_modules pointing at the installed tw-framework bundle.
 * (Monorepo apps that already have a real `@tw/server` are left untouched.)
 */
function ensureTestingShim(rootDir: string): void {
  try {
    const shimPkgDir = join(rootDir, "node_modules", "@tw", "server");
    const marker = join(shimPkgDir, "package.json");
    if (existsSync(marker)) return; // real workspace package or existing shim
    const { mkdirSync, writeFileSync } = _require("node:fs");
    mkdirSync(join(shimPkgDir, "tw"), { recursive: true });
    writeFileSync(marker, JSON.stringify({ name: "@tw/server", version: "1.0.0", private: true }, null, 2));
    // Resolve the testing bundle RELATIVE TO THE RUNNING CLI FILE: bundled
    // installs ship it next to tw.mjs (dist/), source runs reach it two
    // levels up (apps/cli/dist). Works for published AND monorepo setups.
    let testingBundle: string | null = null;
    try {
      const here = new URL(".", import.meta.url).pathname;
      const candidates = [
        join(here, "testing.cjs"),
        join(here, "..", "..", "dist", "testing.cjs"),
      ];
      for (const c of candidates) {
        if (existsSync(c)) { testingBundle = c; break; }
      }
    } catch { /* fall through */ }
    if (!testingBundle) {
      console.warn("  [tw test] testing bundle not found (dist/testing.cjs); test helpers unavailable");
      return;
    }
    writeFileSync(join(shimPkgDir, "tw", "testing.js"),
      "// Generated by `tw test` -- shim pointing at the CLI testing bundle.\n" +
      "module.exports = require(" + JSON.stringify(testingBundle) + ");\n");
  } catch { /* best effort */ }
}

export async function testCommand(): Promise<void> {
  const rootDir = process.cwd();
  const testsDir = join(rootDir, "tests");
  ensureTestingShim(rootDir);

  const files: string[] = [];
  collectTests(testsDir, files);
  // Also pick up root-level *.test.ts
  if (existsSync(rootDir)) {
    for (const f of readdirSync(rootDir)) {
      if (/\.test\.(ts|tsx|js)$/.test(f)) files.push(join(rootDir, f));
    }
  }

  console.log("\n  tw test -- running " + files.length + " test file" + (files.length === 1 ? "" : "s") + "\n");

  if (files.length === 0) {
    console.log("  No tests found. Create tests/your-name.test.ts:");
    console.log(`
    import { test, expect } from "bun:test";
    import { testRoute, testPage } from "@tw/server/tw/testing";

    test("GET /api/health", async () => {
      const res = await testRoute(process.cwd(), "GET", "/api/health");
      expect(res.status).toBe(200);
    });
`);
    process.exit(0);
  }

  // Node runtime: transpile + run in a child process with a bun:test shim.
  // Bun runtime: use the native bun test runner.
  if ((globalThis as any).__TW_NODE) {
    const { runNodeTests } = await import("./node-test-runner");
    const code = await runNodeTests(files, rootDir);
    if (code !== 0) process.exit(code);
    console.log("\n  \x1b[32m✓ Tests passed\x1b[0m\n");
    return;
  }

  const proc = Bun.spawn(["bun", "test", ...files.map(f => join(".", f.replace(rootDir + "/", "")))], {
    cwd: rootDir,
    stdout: "inherit",
    stderr: "inherit",
  });
  const exitCode = await proc.exited;
  if (exitCode !== 0) process.exit(exitCode);
  console.log("\n  \x1b[32m✓ Tests passed\x1b[0m\n");
}
