/**
 * Deno Deploy entry for a TW static build. Generated by `tw adapter deno`.
 *
 * Deno Deploy runs an isolate with no filesystem at request time, so the build
 * output is bundled into the deployment and read once at cold start. Set
 * `--include .tw` (or commit the build) so the files travel with the deploy.
 *
 *   deno run -A server.ts         # local
 *   deployctl deploy server.ts    # Deno Deploy
 */

const OUT_DIR = Deno.env.get("TW_OUT_DIR") ?? ".tw";

/** Preload the build into memory at cold start (isolates have no FS later). */
const files = new Map<string, { body: Uint8Array; type: string }>();

async function preload() {
  async function walk(dir: string) {
    for await (const entry of Deno.readDir(dir)) {
      const path = `${dir}/${entry.name}`;
      if (entry.isDirectory) await walk(path);
      else if (entry.isFile) {
        files.set(path.slice(OUT_DIR.length), {
          body: await Deno.readFile(path),
          type: contentType(entry.name),
        });
      }
    }
  }
  try { await walk(OUT_DIR); } catch { /* nothing built yet */ }
}

function contentType(name: string): string {
  const ext = name.slice(name.lastIndexOf(".") + 1).toLowerCase();
  const map: Record<string, string> = {
    html: "text/html; charset=utf-8", css: "text/css; charset=utf-8",
    js: "text/javascript; charset=utf-8", mjs: "text/javascript; charset=utf-8",
    json: "application/json; charset=utf-8", svg: "image/svg+xml",
    png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg", webp: "image/webp",
    avif: "image/avif", ico: "image/x-icon", woff2: "font/woff2", woff: "font/woff",
    txt: "text/plain; charset=utf-8", xml: "application/xml", map: "application/json",
  };
  return map[ext] ?? "application/octet-stream";
}

/** Resolve a request path to a preloaded file (clean URLs + index + 404). */
function resolve(pathname: string) {
  const candidates = [
    pathname,
    `${pathname}.html`,
    pathname.endsWith("/") ? `${pathname}index.html` : `${pathname}/index.html`,
  ];
  for (const c of candidates) if (files.has(c)) return files.get(c)!;
  return files.get("/404.html") ?? null;
}

await preload();

Deno.serve((req: Request): Response => {
  const url = new URL(req.url);
  const file = resolve(url.pathname);
  if (!file) return new Response("404 Not Found", { status: 404 });
  const isHtml = file.type.startsWith("text/html");
  return new Response(file.body, {
    status: file === files.get("/404.html") ? 404 : 200,
    headers: {
      "Content-Type": file.type,
      "Cache-Control": isHtml ? "public, max-age=0, must-revalidate" : "public, max-age=31536000, immutable",
    },
  });
});
