name: "\U0001F680 Feature request"
description: Suggest an idea for TW Framework
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Tell us what you need and why.
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: What are you trying to do that TW Framework does not support today?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: The solution you would like
      description: A clear description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you have considered
      description: How do you work around this today?
    validations:
      required: false
