#!/usr/bin/env bash
# Deploy the .tw/ build output to AWS S3 + CloudFront.
# Generated by `tw adapter aws`.
#
# Usage:
#   tw build
#   BUCKET=my-bucket DISTRIBUTION_ID=E123ABC bash deploy-s3.sh
#
# Requires the AWS CLI configured with permissions for the bucket
# (and the distribution, when DISTRIBUTION_ID is set).
set -euo pipefail

BUCKET="${BUCKET:?set BUCKET=<your-bucket>}"
DISTRIBUTION_ID="${DISTRIBUTION_ID:-}"

if [ ! -d .tw ]; then
  echo "Run 'tw build' first — .tw/ not found."
  exit 1
fi

# Hashed assets never change — cache them forever.
aws s3 sync .tw/assets "s3://$BUCKET/assets" \
  --cache-control "public, max-age=31536000, immutable" --delete

aws s3 sync .tw/js "s3://$BUCKET/js" \
  --cache-control "public, max-age=31536000, immutable" --delete

# HTML revalidates on every request.
aws s3 sync .tw "s3://$BUCKET" \
  --exclude "assets/*" --exclude "js/*" \
  --cache-control "no-cache" --delete

# Invalidate CloudFront so new HTML is live immediately.
if [ -n "$DISTRIBUTION_ID" ]; then
  aws cloudfront create-invalidation \
    --distribution-id "$DISTRIBUTION_ID" --paths "/*"
fi

echo "Deployed to s3://$BUCKET"
