/** CSS3 properties, aliases, pseudo-classes/elements, functions, at-rules, media. */

export const CSS_PROPERTIES = new Set([
  "display", "position", "top", "right", "bottom", "left", "float", "clear",
  "z-index", "overflow", "overflow-x", "overflow-y", "visibility", "opacity",
  "isolation", "width", "height", "min-width", "min-height", "max-width",
  "max-height", "margin", "margin-top", "margin-right", "margin-bottom",
  "margin-left", "padding", "padding-top", "padding-right", "padding-bottom",
  "padding-left", "border", "border-top", "border-right", "border-bottom",
  "border-left", "border-width", "border-top-width", "border-right-width",
  "border-bottom-width", "border-left-width", "border-style",
  "border-top-style", "border-right-style", "border-bottom-style",
  "border-left-style", "border-color", "border-top-color",
  "border-right-color", "border-bottom-color", "border-left-color",
  "border-radius", "border-top-left-radius", "border-top-right-radius",
  "border-bottom-right-radius", "border-bottom-left-radius",
  "border-image", "border-image-source", "border-image-slice",
  "border-image-width", "border-image-outset", "border-image-repeat",
  "flex", "flex-direction", "flex-wrap", "flex-flow", "justify-content",
  "align-items", "align-self", "align-content", "order", "flex-grow",
  "flex-shrink", "flex-basis", "gap", "row-gap", "column-gap",
  "grid", "grid-template", "grid-template-columns", "grid-template-rows",
  "grid-template-areas", "grid-area", "grid-column", "grid-row",
  "grid-column-start", "grid-column-end", "grid-row-start", "grid-row-end",
  "grid-auto-columns", "grid-auto-rows", "grid-auto-flow", "font",
  "font-family", "font-size", "font-weight", "font-style", "font-variant",
  "font-variant-caps", "font-variant-numeric", "font-variant-ligatures",
  "font-variant-east-asian", "font-stretch", "font-feature-settings",
  "font-kerning", "font-language-override", "font-optical-sizing",
  "font-size-adjust", "font-variation-settings", "line-height",
  "letter-spacing", "word-spacing", "text-align", "text-decoration",
  "text-decoration-line", "text-decoration-style", "text-decoration-color",
  "text-decoration-thickness", "text-indent", "text-transform",
  "text-shadow", "text-overflow", "text-rendering", "text-justify",
  "text-underline-offset", "text-underline-position", "text-emphasis",
  "text-emphasis-color", "text-emphasis-position", "text-emphasis-style",
  "text-wrap", "white-space", "word-break", "word-wrap", "overflow-wrap",
  "line-break", "tab-size", "hyphens", "writing-mode", "direction",
  "unicode-bidi", "vertical-align", "hanging-punctuation", "quotes",
  "orphans", "widows", "color", "background", "background-color",
  "background-image", "background-repeat", "background-attachment",
  "background-position", "background-position-x", "background-position-y",
  "background-clip", "background-origin", "background-size",
  "background-blend-mode", "box-shadow", "box-decoration-break", "filter",
  "backdrop-filter", "mix-blend-mode", "mask", "mask-image", "mask-mode",
  "mask-repeat", "mask-position", "mask-clip", "mask-origin", "mask-size",
  "mask-composite", "mask-border", "mask-border-source", "mask-border-mode",
  "mask-border-slice", "mask-border-width", "mask-border-outset",
  "mask-border-repeat", "clip-path", "clip", "paint-order", "transition",
  "transition-property", "transition-duration", "transition-timing-function",
  "transition-delay", "animation", "animation-name", "animation-duration",
  "animation-timing-function", "animation-delay", "animation-iteration-count",
  "animation-direction", "animation-fill-mode", "animation-play-state",
  "animation-composition", "animation-timeline", "transform",
  "transform-origin", "transform-style", "perspective", "perspective-origin",
  "backface-visibility", "translate", "rotate", "scale", "offset",
  "offset-path", "offset-distance", "offset-rotate", "offset-anchor",
  "offset-position", "container", "container-type", "container-name",
  "list-style", "list-style-type", "list-style-position", "list-style-image",
  "marker-side", "counter-reset", "counter-increment", "counter-set",
  "content", "table-layout", "border-collapse", "border-spacing",
  "caption-side", "empty-cells", "scroll-behavior", "scroll-snap-type",
  "scroll-snap-align", "scroll-snap-stop", "scroll-padding",
  "scroll-padding-top", "scroll-padding-right", "scroll-padding-bottom",
  "scroll-padding-left", "scroll-margin", "scroll-margin-top",
  "scroll-margin-right", "scroll-margin-bottom", "scroll-margin-left",
  "scrollbar-color", "scrollbar-width", "scrollbar-gutter",
  "overscroll-behavior", "overscroll-behavior-x", "overscroll-behavior-y",
  "view-transition-name", "will-change", "appearance", "caret-color",
  "cursor", "outline", "outline-width", "outline-style", "outline-color",
  "outline-offset", "resize", "user-select", "accent-color",
  "content-visibility", "forced-color-adjust", "columns", "column-count",
  "column-fill", "column-gap", "column-rule", "column-rule-color",
  "column-rule-style", "column-rule-width", "column-span", "column-width",
  "break-after", "break-before", "break-inside", "page", "page-break-after",
  "page-break-before", "page-break-inside", "all", "box-sizing", "contain",
  "contain-intrinsic-size", "contain-intrinsic-width",
  "contain-intrinsic-height", "input-security", "aspect-ratio",
  "object-fit", "object-position", "image-orientation", "image-rendering",
  "image-resolution", "shape-outside", "shape-image-threshold",
  "shape-margin", "zoom", "fill", "fill-opacity", "fill-rule", "stroke",
  "stroke-width", "stroke-linecap", "stroke-linejoin", "stroke-miterlimit",
  "stroke-dasharray", "stroke-dashoffset", "stroke-opacity",
  "color-interpolation", "color-interpolation-filters", "color-rendering",
  "dominant-baseline", "alignment-baseline", "baseline-shift", "text-anchor",
  "shape-rendering", "stop-color", "stop-opacity", "flood-color",
  "flood-opacity", "lighting-color", "glyph-orientation-horizontal",
  "glyph-orientation-vertical", "kerning", "vector-effect", "mask-type",
]);

export const CSS_ALIASES: Record<string, string> = {
  "bg": "background", "bg-color": "background-color", "bg-image": "background-image",
  "bg-size": "background-size", "bg-position": "background-position",
  "bg-repeat": "background-repeat", "bg-clip": "background-clip",
  "bg-origin": "background-origin", "bg-attachment": "background-attachment",
  "bd": "border", "bd-top": "border-top", "bd-right": "border-right",
  "bd-bottom": "border-bottom", "bd-left": "border-left",
  "bd-width": "border-width", "bd-style": "border-style", "bd-color": "border-color",
  "bd-radius": "border-radius", "pd": "padding", "pd-top": "padding-top",
  "pd-right": "padding-right", "pd-bottom": "padding-bottom",
  "pd-left": "padding-left", "mg": "margin", "mg-top": "margin-top",
  "mg-right": "margin-right", "mg-bottom": "margin-bottom", "mg-left": "margin-left",
  "fs": "font-size", "fw": "font-weight", "ff": "font-family",
  "lh": "line-height", "ls": "letter-spacing", "ws": "word-spacing",
  "ta": "text-align", "td": "text-decoration", "tt": "text-transform",
  "ti": "text-indent", "ts": "text-shadow", "to": "text-overflow",
  "ww": "word-wrap", "wb": "word-break", "va": "vertical-align",
  "d": "display", "pos": "position", "fl": "float", "cl": "clear",
  "zi": "z-index", "ov": "overflow", "ovx": "overflow-x", "ovy": "overflow-y",
  "vis": "visibility", "op": "opacity", "cur": "cursor", "ol": "outline",
  "bs": "box-shadow", "bz": "box-sizing", "br": "border-radius",
  "w": "width", "h": "height", "mw": "min-width", "mh": "min-height",
  "Mw": "max-width", "Mh": "max-height", "fx": "flex", "fxd": "flex-direction",
  "fxw": "flex-wrap", "jc": "justify-content", "ai": "align-items",
  "as": "align-self", "ac": "align-content", "fxg": "flex-grow",
  "fxs": "flex-shrink", "fxb": "flex-basis", "gr": "grid",
  "grt": "grid-template", "grtc": "grid-template-columns",
  "grtr": "grid-template-rows", "grta": "grid-template-areas", "gra": "grid-area",
  "tr": "transition", "trp": "transition-property", "trd": "transition-duration",
  "an": "animation", "tf": "transform", "tfo": "transform-origin",
  "ft": "filter", "bft": "backdrop-filter", "cp": "clip-path", "msk": "mask",
  "ar": "aspect-ratio", "of": "object-fit", "us": "user-select", "ap": "appearance",
};

export const NUMERIC_CSS = new Set([
  "z-index", "opacity", "font-weight", "flex-grow", "flex-shrink", "order",
  "line-height", "font-size-adjust", "stroke-miterlimit", "stroke-opacity",
  "fill-opacity", "stop-opacity", "flood-opacity", "shape-image-threshold",
  "animation-iteration-count",
]);

export const CSS_LENGTH_UNITS = new Set([
  "px", "em", "rem", "vh", "vw", "vmin", "vmax", "vi", "vb", "svh", "svw",
  "svmin", "svmax", "lvh", "lvw", "lvmin", "lvmax", "dvh", "dvw", "dvmin",
  "dvmax", "ex", "ch", "cm", "mm", "in", "pt", "pc", "q", "fr", "%", "deg",
  "rad", "grad", "turn", "s", "ms", "Hz", "kHz", "dpi", "dpcm", "dppx", "x",
]);

export const CSS_PSEUDO_CLASSES = new Set([
  "active", "any-link", "blank", "checked", "default", "defined", "dir",
  "disabled", "empty", "enabled", "first", "first-child", "first-of-type",
  "fullscreen", "future", "focus", "focus-visible", "focus-within", "host",
  "host-context", "hover", "in-range", "indeterminate", "invalid", "is",
  "lang", "last-child", "last-of-type", "left", "link", "local-link", "not",
  "nth-child", "nth-last-child", "nth-last-of-type", "nth-of-type",
  "only-child", "only-of-type", "optional", "out-of-range", "past",
  "placeholder-shown", "popover-open", "read-only", "read-write", "required",
  "right", "root", "scope", "target", "valid", "visited", "where",
]);

export const CSS_PSEUDO_ELEMENTS = new Set([
  "after", "backdrop", "before", "cue", "first-letter", "first-line",
  "grammar-error", "marker", "placeholder", "selection", "spelling-error",
  "target-text", "file-selector-button", "details-content", "search-text",
  "view-transition", "view-transition-group", "view-transition-image-pair",
  "view-transition-old", "view-transition-new",
]);

export const CSS_FUNCTIONS = new Set([
  "var", "env", "calc", "min", "max", "clamp", "abs", "sign", "round", "mod",
  "rem", "sin", "cos", "tan", "asin", "acos", "atan", "atan2", "pow", "sqrt",
  "hypot", "log", "exp", "random", "rgb", "rgba", "hsl", "hsla", "hwb", "lch",
  "lab", "oklch", "oklab", "color", "color-mix", "color-contrast",
  "device-cmyk", "url", "image", "image-set", "cross-fade", "element",
  "linear-gradient", "radial-gradient", "conic-gradient",
  "repeating-linear-gradient", "repeating-radial-gradient",
  "repeating-conic-gradient", "matrix", "matrix3d", "perspective", "rotate",
  "rotate3d", "rotateX", "rotateY", "rotateZ", "scale", "scale3d", "scaleX",
  "scaleY", "scaleZ", "skew", "skewX", "skewY", "steps", "translate",
  "translate3d", "translateX", "translateY", "translateZ", "cubic-bezier",
  "linear", "ease", "ease-in", "ease-out", "ease-in-out", "step-start",
  "step-end", "frames", "path", "ray", "fit-content", "min-content",
  "max-content", "stretch", "repeat", "minmax", "auto-fit", "auto-fill",
  "counter", "counters", "symbols", "attr", "content", "string", "leader",
  "target-counter", "target-text", "running", "anchor", "anchor-size",
  "anchor-name",
]);

export const CSS_AT_RULES = new Set([
  "@charset", "@import", "@namespace", "@media", "@supports", "@page",
  "@font-face", "@keyframes", "@viewport", "@counter-style",
  "@font-feature-values", "@property", "@layer", "@container", "@scope",
  "@starting-style", "@view-transition",
]);

export const CSS_MEDIA_FEATURES = new Set([
  "width", "min-width", "max-width", "height", "min-height", "max-height",
  "aspect-ratio", "orientation", "block-size", "inline-size",
  "min-block-size", "max-block-size", "min-inline-size", "max-inline-size",
  "resolution", "min-resolution", "max-resolution", "scan", "grid", "color",
  "min-color", "max-color", "color-index", "min-color-index",
  "max-color-index", "monochrome", "min-monochrome", "max-monochrome",
  "color-gamut", "dynamic-range", "inverted-colors", "forced-colors",
  "prefers-color-scheme", "prefers-contrast", "prefers-reduced-transparency",
  "prefers-reduced-motion", "prefers-reduced-data", "pointer", "any-pointer",
  "hover", "any-hover", "nav-controls", "light-level", "scripting",
  "environment-blending", "viewport-fit", "device-width", "device-height",
  "device-aspect-ratio", "overflow-inline", "overflow-block", "update",
  "display-mode", "transform-3d", "viewport-segments", "display-state",
]);
